name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 1.1.1
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  archive: ^2.0.13
  xml: ^4.2.0

dev_dependencies:
  path: ^1.7.0
  pedantic: ^1.9.2
  test: ^1.15.3
