name: spreadsheet_decoder
description: Spreadsheet files decoder
version: 0.4.1-alpha
authors:
- St√©phane Este-Gracias <sestegra@gmail.com>
homepage: https://github.com/sestegra/spreadsheet
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  archive: '^1.0.33'
  xml: '^3.0.0-alpha'
dev_dependencies:
  test: '^0.12.0'
