name: spreadsheet_decoder
description: A lightweight library for parsing and updating spreadsheet documents
version: 1.1.0
authors:
- St√©phane Este-Gracias <sestegra@gmail.com>
homepage: https://github.com/sestegra/spreadsheet

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  xml: ^3.0.0

dev_dependencies:
  path: ^1.5.1
  test: ^1.2.0
